import {RouteInfo} from "./RouteMetadata";

export const ROUTES: RouteInfo[] = [
  {
    path: '',
    title: 'MENUITEMS.TITLES.MAIN',
    iconType: '',
    icon: '',
    class: '',
    groupTitle: true,
    badge: '',
    badgeClass: '',
    submenu: [],
  },
  {
    path: 'dashboard/HomePage',
    title: 'MENUITEMS.USER.HOME',
    iconType: 'feather',
    icon: 'home',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [],
  },

];

export const ROUTESADMIN: RouteInfo[] = [
  {
    path: '',
    title: 'MENUITEMS.TITLES.MAIN',
    iconType: '',
    icon: '',
    class: '',
    groupTitle: true,
    badge: '',
    badgeClass: '',
    submenu: [],
  },
  {
    path: 'dashboard/HomePage',
    title: 'MENUITEMS.ADMIN.HOME',
    iconType: 'feather',
    icon: 'home',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [],
  },
  {
    path: '',
    title: 'MENUITEMS.ADMIN.COMBOGESTIONE.TITLE',
    iconType: 'feather',
    icon: 'leaf',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [
      {
        path: 'dashboard/HomePage2',
        title: 'MENUITEMS.ADMIN.COMBOGESTIONE.OPERATORI',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        submenu: [],
      },
      {
        path: 'dashboard/dashboard2',
        title: 'MENUITEMS.ADMIN.COMBOGESTIONE.OPERATORIFR',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        submenu: [],
      },
      {
        path: 'dashboard/dashboard2',
        title: 'MENUITEMS.ADMIN.COMBOGESTIONE.CLIENTI',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        submenu: [],
      },
      {
        path: 'dashboard/dashboard2',
        title: 'MENUITEMS.ADMIN.COMBOGESTIONE.RICHIESTE',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        submenu: [],
      },
    ],
  },

  {
    path: '',
    title: 'MENUITEMS.ADMIN.COMBOSISTEMA.TITLE',
    iconType: 'feather',
    icon: 'leaf',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [
      {
        path: 'dashboard/HomePage2',
        title: 'MENUITEMS.ADMIN.COMBOSISTEMA.LOGSISTEMA',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        submenu: [],
      },
      {
        path: 'dashboard/dashboard2',
        title: 'MENUITEMS.ADMIN.COMBOSISTEMA.LOGRICHIESTE',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        submenu: [],
      },
    ],
  },

];
